#!/bin/bash

KLIPPERSCREEN_USER=print3D
KLIPPERSCREEN_CONFIG=/home/$KLIPPERSCREEN_USER/printer_data/config/KlipperScreen.conf
KLIPPERSCREEN_LOG=/home/$KLIPPERSCREEN_USER/printer_data/logs/KlipperScreen.log

/home/$KLIPPERSCREEN_USER/.KlipperScreen-env/bin/python /home/$KLIPPERSCREEN_USER/KlipperScreen/screen.py -c $KLIPPERSCREEN_CONFIG -l $KLIPPERSCREEN_LOG
